In [1]:
import numpy as np
import pandas as pd

In [17]:
file = 'train.csv'
proc_file = 'processed_train.csv'

# Start preprocessing dataset

In [21]:
df = pd.read_csv(file, names=[f'col_{i}' for i in range(100)])

In [22]:
df

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_90,col_91,col_92,col_93,col_94,col_95,col_96,col_97,col_98,col_99
0,0.097094,1.11330,45.038,0.88184,0.087009,1.04100,1.548600,3.49800,1.85780,0.009673,...,0.076209,3.66540,0.061607,0.003161,0.036038,0.084500,2.45170,3.3373,0.065201,0.091158
1,0.050086,0.11158,94.080,1.76500,0.089417,4.80470,0.267420,NaN,0.56473,0.035123,...,0.054712,4.16870,0.075432,0.010869,0.063972,0.079892,1.97950,3.5064,0.072132,0.091950
2,0.088447,2.36340,5.058,0.14436,0.064547,2.44400,4.254500,0.36506,1.86090,0.009759,...,0.017203,4.56130,0.046505,NaN,0.084066,0.064829,3.30870,2.9969,0.064328,0.036793
3,0.772540,0.59469,NaN,0.97515,0.015987,0.52884,1.488400,3.96100,4.80630,0.048617,...,0.022891,0.12832,0.065028,0.036862,0.010010,0.020709,2.52370,2.1711,0.080865,0.081553
4,0.382410,4.81090,1955.100,0.46050,0.024453,2.02980,3.740300,4.22810,2.42920,0.156830,...,0.032051,4.37010,1.001100,0.065750,0.043547,0.629430,4.62620,3.1947,NaN,0.187180
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,0.083012,4.44000,1140.100,5.04650,0.069693,4.32170,2.652700,4.80340,4.91870,0.088879,...,0.054703,3.50690,0.518980,0.047767,0.061994,0.256460,3.57210,4.7692,0.056299,0.162660
596,0.523780,3.32790,122.050,3.54630,1.010900,1.72230,3.131200,3.75900,3.61270,0.061250,...,0.351960,1.55980,0.023365,1.084000,0.072553,0.049359,3.46930,3.1465,0.031458,0.019107
597,0.995510,1.60620,464.090,3.58910,0.091039,1.62010,3.688400,1.84550,0.41606,0.548030,...,0.114580,3.32090,0.019906,0.057709,0.097567,0.073208,0.62583,4.6044,0.071155,0.053476
598,1.208000,2.10000,24.011,2.92140,0.055663,0.78477,1.288900,3.18080,4.77850,0.050453,...,0.011022,2.48810,0.061171,0.070312,NaN,0.043862,0.58203,4.5994,0.045182,0.031991
599,0.083476,2.86980,37.074,3.08970,0.086909,4.91600,0.087911,2.55460,2.13250,0.069508,...,0.615660,0.12656,0.085419,0.002887,0.007303,0.009501,4.80320,1.7190,0.054735,0.035035

In [23]:
df.describe()

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_90,col_91,col_92,col_93,col_94,col_95,col_96,col_97,col_98,col_99
count,585.000000,590.000000,580.000000,580.000000,575.000000,584.000000,587.000000,583.000000,581.000000,581.000000,...,579.000000,585.000000,584.000000,578.000000,571.000000,583.000000,584.000000,582.000000,581.000000,574.000000
mean,0.326534,2.557716,290.594555,2.643836,0.182192,2.510491,2.642292,2.552223,2.501381,0.127933,...,0.083359,2.532718,0.174124,0.094121,0.174487,0.111907,2.538155,2.604494,0.182136,0.152312
std,0.545283,1.433982,621.384645,1.446750,0.420896,1.449157,1.472695,1.449577,1.451475,0.386757,...,0.194025,1.442497,0.610803,0.366975,0.564201,0.217228,1.458332,1.419637,0.559075,0.302947
min,0.000445,0.055685,1.007800,0.032513,0.000100,0.014350,0.016254,0.039126,0.036541,0.000090,...,0.000209,0.020904,0.000178,0.000131,0.000338,0.000447,0.020070,0.045843,0.000553,0.000018
25%,0.042475,1.350800,36.064500,1.507225,0.031295,1.227850,1.315500,1.359000,1.191100,0.027302,...,0.029454,1.278400,0.031738,0.028466,0.028071,0.030587,1.309775,1.333325,0.033025,0.027419
50%,0.079607,2.551650,93.057500,2.592850,0.060399,2.564750,2.772000,2.509600,2.452900,0.055708,...,0.054983,2.591700,0.061565,0.051281,0.056169,0.057634,2.453500,2.607300,0.057666,0.057452
75%,0.416470,3.787175,278.797500,3.951500,0.086785,3.694850,3.905600,3.809350,3.739300,0.084026,...,0.082530,3.759300,0.088392,0.076579,0.083925,0.086606,3.829200,3.868500,0.086263,0.092728
max,5.176600,5.064400,9163.100000,5.092100,4.605000,5.088200,5.056600,5.088800,5.072300,4.347800,...,3.838700,5.058300,11.120000,7.208400,5.217900,2.383400,5.073700,5.081900,7.693400,3.588100

In [24]:
[df.iloc[:,i].sum() for i in range(df.shape[1])]

[191.02234988,
 1509.052261,
 168544.8417,
 1533.425005,
 104.76017876,
 1466.126671,
 1551.02538,
 1487.945839,
 1453.302338,
 74.32924886,
 1479.140249,
 1586.8141260000002,
 75.94573376,
 1454.2748660000002,
 1499.8690500000002,
 1503.2018159000002,
 378.993937124,
 1482.2607669999998,
 1488.205473,
 81.52232677,
 76.47310206,
 38.29757114,
 1475.20071,
 80.27694293900001,
 90.82577233,
 1506.5196270000001,
 1467.0460699999999,
 74.60490166,
 128.20177671,
 1446.8801159999998,
 89.68740856,
 85.71169983000001,
 112.65991807,
 43.47213927,
 1494.6347420000002,
 28212.524400000002,
 1002.2590127000001,
 1490.798882,
 1411.8697789999999,
 331.00362957000004,
 1476.8261710000002,
 1488.242402,
 77.72690834,
 1420.502998,
 2724.9193,
 1531.796611,
 106.51456543199998,
 1509.4957339999999,
 67.32964898545,
 144.62836462,
 1478.476451,
 73.37470526,
 181.81095041999998,
 73.241614068,
 1459.7683710000001,
 1480.2577489999999,
 208.9463163604,
 1530.204327,
 60.170641229999994,
 112.173340088,
 55.06651814999999,
 73.18015928,
 103.3127082,
 207.48580437,
 51.595372075,
 1475.173535,
 1475.4291320000002,
 1458.020113,
 101.577457231,
 130.34374037999999,
 1493.267234,
 1496.3546769999998,
 86.755484648,
 32.013734806,
 1471.457801,
 123.77977247000001,
 165.996430245,
 1458.31921,
 55.8296285,
 198.29878735,
 1471.251424,
 563.55536327,
 1525.124132,
 92.08029503,
 476.86165380700004,
 1492.4713590000001,
 1529.888966,
 182.24119889,
 216.186509573,
 40.642985503000006,
 48.26507058,
 1481.639975,
 101.68826290999999,
 54.40218661,
 99.63229233999999,
 65.24166334,
 1482.282725,
 1515.815767,
 105.82116388999998,
 87.427227229]

# Filling in NaN values with means

In [25]:
for i in range(df.shape[1]):
    df.iloc[:, i].fillna(df.iloc[:, i].mean(), inplace=True)

In [26]:
[df.iloc[:,i].sum() for i in range(df.shape[1])]

[195.92035885128206,
 1534.6294179661018,
 174356.73279310344,
 1586.3017293103449,
 109.31496914086958,
 1506.294525,
 1585.375175468484,
 1531.3336250428817,
 1500.8285762478486,
 76.75998161101549,
 1511.8980398637138,
 1630.2884856164385,
 77.7601369556314,
 1512.2442280762566,
 1570.543507853403,
 1544.3854272945207,
 393.4193118934256,
 1512.5109867346937,
 1531.6008298456263,
 84.47909509844558,
 78.70302098799313,
 39.686602217616574,
 1513.0263692307694,
 82.7597349886598,
 93.47420822984563,
 1529.4615502538072,
 1496.9857857142856,
 76.91226975257732,
 131.48900175384614,
 1496.7725337931035,
 93.58686110608696,
 88.3625771443299,
 114.37555134010151,
 44.434895335604764,
 1540.8605587628867,
 29035.18806174957,
 1040.4072796193773,
 1539.5513411359725,
 1463.07749119171,
 338.91156611262795,
 1530.389814507772,
 1539.5611055172412,
 79.58386519453926,
 1472.0238321243523,
 2790.01976109215,
 1576.4630644939966,
 108.68833207346938,
 1545.558772013652,
 69.05605024148718,
 147.5799638979592,
 1516.3861035897435,
 75.90486751034483,
 189.05818067937608,
 74.8636600354344,
 1517.956711611785,
 1533.9458538860104,
 213.21052689836733,
 1585.703965803109,
 61.81915194863014,
 114.4625919265306,
 57.06374937823834,
 74.67363191836735,
 105.60072388415674,
 212.08089032708688,
 53.37452283620689,
 1533.9759462738302,
 1526.3059986206897,
 1513.515688235294,
 104.18200741641026,
 134.37499008247423,
 1550.1043951557092,
 1529.4937073253834,
 88.37570592325976,
 32.72272722930154,
 1519.5777635111876,
 128.26919426943005,
 171.1303404587629,
 1503.4218659793814,
 57.95463166089965,
 202.34570137755102,
 1508.9758194871795,
 585.0055674083045,
 1572.292919587629,
 94.76531220926245,
 495.0120973775086,
 1541.2785118760758,
 1577.2051195876288,
 186.27720499829644,
 220.9742857645656,
 41.613978330716726,
 50.01561718134715,
 1519.6307435897436,
 104.47424271575342,
 56.472858072664366,
 104.69242627670752,
 67.14407890909091,
 1522.8932106164384,
 1562.6966670103093,
 109.2817527263339,
 91.38734553554006]

In [27]:
df.to_csv("processed_train.csv", index=False)

# Checking Processed File

In [28]:
df2 = pd.read_csv(proc_file)

In [29]:
df2

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_90,col_91,col_92,col_93,col_94,col_95,col_96,col_97,col_98,col_99
0,0.097094,1.11330,45.038000,0.88184,0.087009,1.04100,1.548600,3.498000,1.85780,0.009673,...,0.076209,3.66540,0.061607,0.003161,0.036038,0.084500,2.45170,3.3373,0.065201,0.091158
1,0.050086,0.11158,94.080000,1.76500,0.089417,4.80470,0.267420,2.552223,0.56473,0.035123,...,0.054712,4.16870,0.075432,0.010869,0.063972,0.079892,1.97950,3.5064,0.072132,0.091950
2,0.088447,2.36340,5.058000,0.14436,0.064547,2.44400,4.254500,0.365060,1.86090,0.009759,...,0.017203,4.56130,0.046505,0.094121,0.084066,0.064829,3.30870,2.9969,0.064328,0.036793
3,0.772540,0.59469,290.594555,0.97515,0.015987,0.52884,1.488400,3.961000,4.80630,0.048617,...,0.022891,0.12832,0.065028,0.036862,0.010010,0.020709,2.52370,2.1711,0.080865,0.081553
4,0.382410,4.81090,1955.100000,0.46050,0.024453,2.02980,3.740300,4.228100,2.42920,0.156830,...,0.032051,4.37010,1.001100,0.065750,0.043547,0.629430,4.62620,3.1947,0.182136,0.187180
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,0.083012,4.44000,1140.100000,5.04650,0.069693,4.32170,2.652700,4.803400,4.91870,0.088879,...,0.054703,3.50690,0.518980,0.047767,0.061994,0.256460,3.57210,4.7692,0.056299,0.162660
596,0.523780,3.32790,122.050000,3.54630,1.010900,1.72230,3.131200,3.759000,3.61270,0.061250,...,0.351960,1.55980,0.023365,1.084000,0.072553,0.049359,3.46930,3.1465,0.031458,0.019107
597,0.995510,1.60620,464.090000,3.58910,0.091039,1.62010,3.688400,1.845500,0.41606,0.548030,...,0.114580,3.32090,0.019906,0.057709,0.097567,0.073208,0.62583,4.6044,0.071155,0.053476
598,1.208000,2.10000,24.011000,2.92140,0.055663,0.78477,1.288900,3.180800,4.77850,0.050453,...,0.011022,2.48810,0.061171,0.070312,0.174487,0.043862,0.58203,4.5994,0.045182,0.031991
599,0.083476,2.86980,37.074000,3.08970,0.086909,4.91600,0.087911,2.554600,2.13250,0.069508,...,0.615660,0.12656,0.085419,0.002887,0.007303,0.009501,4.80320,1.7190,0.054735,0.035035